#!/usr/bin/env bash
set -euo pipefail

ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
hwclock --systohc

sed -i '/en_GB.UTF-8/s/^#//' /etc/locale.gen
locale-gen
echo "LANG=en_GB.UTF-8" >> /etc/locale.conf

echo "CrescentLibrary" >> /etc/hostname

passwd

read -p "Enter a username: " username && sudo useradd -m -g users -G wheel "$username"
passwd "$username"
echo "$username ALL=(ALL) ALL" >> /etc/sudoers.d/"$username"

sed -i '/^MODULES=/s/)/btrfs)/' /etc/mkinitcpio.conf
sed -i '/^HOOKS=/s/)/base udev autodetect microcode modconf kms keyboard keymap consolefont block encrypt filesystems resume fsck)/' /etc/mkinitcpio.conf
mkinitcpio -P

grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=Arch
grub-mkconfig -o /boot/grub/grub.cfg

UUID_ROOT=$(blkid -s UUID -o value /dev/nvme0n1p3)
UUID_SWAP=$(blkid -s UUID -o value /dev/nvme0n1p2)

sed -i "/^GRUB_CMDLINE_LINUX_DEFAULT=/s|\"$| loglevel=3 quiet cryptdevice=UUID=$UUID_ROOT root=/dev/mapper/main resume=UUID=$UUID_SWAP\"|" /etc/default/grub

grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable NetworkManager
systemctl enable bluetooth
systemctl enable ufw

lsblk
fastfetch
exit
