#!/usr/bin/env bash
set -euo pipefail

lsblk

parted /dev/nvme0n1 mklabel gpt
parted -a optimal /dev/nvme0n1 mkpart primary fat32 1MiB 1GiB
parted /dev/nvme0n1 set 1 boot on
mkfs.fat -F32 /dev/nvme0n1p1

parted -a optimal /dev/nvme0n1 mkpart primary linux-swap 1GiB 17GiB
mkswap /dev/nvme0n1p2
swapon /dev/nvme0n1p2

parted -a optimal /dev/nvme0n1 mkpart primary 17GiB 100%
cryptsetup luksFormat /dev/nvme0n1p3
cryptsetup open /dev/nvme0n1p3 main
mkfs.btrfs /dev/mapper/main

mount /dev/mapper/main /mnt
cd /mnt
btrfs subvolume create @
btrfs subvolume create @home
cd
pwd
umount /mnt

mount -o noatime,ssd,compress=zstd,space_cache=v2,discard=async,subvol=@ /dev/mapper/main /mnt
mkdir /mnt/home
mount -o noatime,ssd,compress=zstd,space_cache=v2,discard=async,subvol=@home /dev/mapper/main /mnt/home
mkdir /mnt/boot
mount /dev/nvme0n1p1 /mnt/boot

lsblk

pacman-key --init
pacman-key --populate archlinux
pacstrap /mnt base linux-lts linux-lts-headers linux-firmware nvim base-devel grub efibootmgr networkmanager git nvidia-open-lts nvidia-utils sudo --needed

genfstab -U -p /mnt >> /mnt/etc/fstab
cat /mnt/etc/fstab

arch-chroot /mnt

ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
hwclock --systohc

sed -i '/en_GB.UTF-8/s/^#//' /etc/locale.gen
locale-gen
echo "LANG=en_GB.UTF-8" >> /etc/locale.conf

echo "CrescentLibrary" >> /etc/hostname

passwd

read -p "Enter a username: " username && sudo useradd -m -g users -G wheel "$username"
passwd "$username"
echo "$username ALL=(ALL) ALL" >> /etc/sudoers.d/"$username"

sed -i '/^MODULES=/c\MODULES=(btrfs)' /etc/mkinitcpio.conf
sed -i '/^HOOKS=/c\HOOKS=(base udev autodetect microcode modconf kms keyboard keymap consolefont block encrypt filesystems resume fsck)'/etc/mkinitcpio.conf


grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=Arch
grub-mkconfig -o /boot/grub/grub.cfg

UUID_ROOT=$(blkid -s UUID -o value /dev/nvme0n1p3)
UUID_SWAP=$(blkid -s UUID -o value /dev/nvme0n1p2)

sed -i "/^GRUB_CMDLINE_LINUX_DEFAULT=/s|\"$| loglevel=3 quiet cryptdevice=UUID=$UUID_ROOT root=/dev/mapper/main resume=UUID=$UUID_SWAP\"|" /etc/default/grub

grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable NetworkManager
systemctl enable bluetooth
systemctl enable ufw

lsblk
fastfetch
exit
